services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./init-db1.sql:/docker-entrypoint-initdb.d/init.sql

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - ./init-db2.sql:/docker-entrypoint-initdb.d/init.sql

  mysql1:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db3
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./init-db3.sql:/docker-entrypoint-initdb.d/init.sql

